#!/usr/bin/env python3
"""Build deterministic browser assets for the bundled AI-animation library."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


SKILL_DIR = Path(__file__).resolve().parents[2]
CATALOG = SKILL_DIR / "ai_animation" / "typography" / "catalog.json"
CATALOG_JS = SKILL_DIR / "ai_animation" / "typography" / "runtime" / "text-effects-catalog.js"


def render_catalog_js(catalog: dict) -> str:
    payload = json.dumps(catalog, ensure_ascii=False, indent=2)
    return (
        "/* Generated by scripts/ai_animation/build_assets.py. Do not edit directly. */\n"
        f"globalThis.VideoMasterTextEffectCatalog = {payload};\n"
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail when generated assets are stale")
    args = parser.parse_args(argv)

    catalog = json.loads(CATALOG.read_text(encoding="utf-8"))
    expected = render_catalog_js(catalog)
    if args.check:
        if not CATALOG_JS.is_file() or CATALOG_JS.read_text(encoding="utf-8") != expected:
            print(f"ERROR: stale generated file: {CATALOG_JS}")
            return 1
        print(f"OK: {CATALOG_JS}")
        return 0

    CATALOG_JS.parent.mkdir(parents=True, exist_ok=True)
    CATALOG_JS.write_text(expected, encoding="utf-8")
    print(CATALOG_JS)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
